# Generated by Django 4.2.7 on 2025-03-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="greenhouse",
            old_name="next_harvest",
            new_name="next_harvest_date",
        ),
        migrations.RenameField(
            model_name="greenhouse",
            old_name="planted_date",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="air_flow",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="automation_status",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="co2_level",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="current_stage",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="expected_yield",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="health",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="light_intensity",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="production_trend",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="soil_moisture",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="weekly_production",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="weekly_revenue",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Farm Manager"),
                    ("owner", "Farm Owner"),
                    ("admin", "Admin"),
                ],
                default="owner",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("irrigation", "Irrigation"),
                            ("spraying", "Spraying"),
                            ("fertilizer", "Fertilizer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("missed", "Missed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api_app.greenhouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Harvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvests",
                        to="api_app.greenhouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("task", "Task Reminder"),
                            ("harvest", "Harvest Reminder"),
                            ("system", "System Alert"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api_app.greenhouse",
                    ),
                ),
            ],
        ),
    ]
