# Generated by Django 4.2.7 on 2025-03-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0002_rename_next_harvest_greenhouse_next_harvest_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harvest",
            name="greenhouse",
        ),
        migrations.RemoveField(
            model_name="tasklog",
            name="greenhouse",
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="next_harvest_date",
        ),
        migrations.RemoveField(
            model_name="greenhouse",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="favorite_color",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="greenhouse",
            name="size",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.DeleteModel(
            name="Harvest",
        ),
        migrations.DeleteModel(
            name="TaskLog",
        ),
    ]
