# Generated by Django 4.2.7 on 2025-04-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "api_app",
            "0003_remove_harvest_greenhouse_remove_tasklog_greenhouse_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("seed_type", models.CharField(max_length=100)),
                ("planting_date", models.DateField()),
                ("expected_harvest_date", models.DateField()),
                ("actual_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("growing", "Growing"),
                            ("harvesting", "Harvesting"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated Early"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "termination_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("harvest_complete", "Harvest Completed"),
                            ("crop_failure", "Crop Failure"),
                            ("disease", "Disease"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("termination_notes", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("cleaning", "Cleaning"), ("repair", "Repair")],
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[("planned", "Planned"), ("unplanned", "Unplanned")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyHarvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("harvest_date", models.DateField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("medium", "Medium"),
                            ("bad", "Bad"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "growing_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvests",
                        to="api_app.growingcycle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="greenhouse",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("active", "Active"),
                    ("maintenance", "Maintenance"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="greenhouse",
            name="size",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="GreenhouseActivity",
        ),
        migrations.AddField(
            model_name="maintenanceactivity",
            name="greenhouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance",
                to="api_app.greenhouse",
            ),
        ),
        migrations.AddField(
            model_name="growingcycle",
            name="greenhouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles",
                to="api_app.greenhouse",
            ),
        ),
    ]
