# Generated by Django 4.2.7 on 2025-04-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0004_growingcycle_maintenanceactivity_weeklyharvest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("ml", "Milliliters"),
                            ("l", "Liters"),
                            ("g", "Grams"),
                            ("kg", "Kilograms"),
                            ("bottle", "Bottles"),
                            ("pack", "Packs"),
                        ],
                        max_length=10,
                    ),
                ),
                ("concentration", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.DecimalField(decimal_places=2, max_digits=10)),
                ("usage_date", models.DateTimeField(auto_now_add=True)),
                ("purpose_note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="api_app.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
