# Generated by Django 4.2.7 on 2025-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0006_inventoryusage_greenhouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingcycle",
            name="stage",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="growingcycle",
            name="stage_name",
            field=models.CharField(default="Germination", max_length=50),
        ),
        migrations.AddField(
            model_name="growingcycle",
            name="total_stages",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="growingcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("germination", "Germination"),
                    ("seedling", "Seedling"),
                    ("vegetative_growth", "Vegetative Growth"),
                    ("flowering", "Flowering"),
                    ("maturation", "Maturation"),
                    ("completed", "Completed"),
                    ("terminated", "Terminated Early"),
                ],
                default="germination",
                max_length=20,
            ),
        ),
    ]
